{
 "title": "Kubernetes All Nodes",
 "description": "Dashboard to get an overview of all nodes in a Kubernetes Cluster",
 "tags": [ "prometheus" ],
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Memory Utilization",
   "type": "timeseries",
   "description": "Memory Utilization",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "((sum(node_memory_MemTotal_bytes{instance=~\"node.*\"}) - sum(node_memory_MemFree_bytes{instance=~\"node.*\"}) - sum(node_memory_Buffers_bytes{instance=~\"node.*\"}) - sum(node_memory_Cached_bytes{instance=~\"node.*\"})) / sum(node_memory_MemTotal_bytes{instance=~\"node.*\"})) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System load",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "sum(node_load1) / 2", "legendFormat": "load 1m" },
    { "expr": "sum(node_load5) /2", "legendFormat": "load 5m" },
    { "expr": "sum(node_load15) / 2", "legendFormat": "load 15m" }
   ]
  },
  {
   "title": "Disk space usage",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(node_filesystem_size_bytes{device!=\"/\"}) - sum(node_filesystem_free_bytes{device!=\"/\"})) / sum(node_filesystem_size_bytes{device!=\"/\"})"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "description": "CPU Utilization",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode=\"user\", instance=~\"node.*\"}[2m])) * 100 * 2",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "((sum(node_memory_MemTotal_bytes) - sum(node_memory_MemFree_bytes) - sum(node_memory_Buffers_bytes) - sum(node_memory_Cached_bytes)) / sum(node_memory_MemTotal_bytes)) * 100"
    }
   ]
  },
  {
   "title": "Idle cpu",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode=\"idle\"}[2m])) * 100 / 2"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes) - sum(node_memory_MemFree_bytes) - sum(node_memory_Buffers_bytes) - sum(node_memory_Cached_bytes)",
     "legendFormat": "memory usage"
    },
    { "expr": "sum(node_memory_Buffers_bytes)", "legendFormat": "memory buffers" },
    { "expr": "sum(node_memory_Cached_bytes)", "legendFormat": "memory cached" },
    { "expr": "sum(node_memory_MemFree_bytes)", "legendFormat": "memory free" }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(node_nfsd_disk_bytes_read_total[5m]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum(rate(node_nfsd_disk_bytes_written_total[5m]))",
     "legendFormat": "written"
    },
    {
     "expr": "sum(rate(node_disk_io_time_seconds_total[5m]))",
     "legendFormat": "io time"
    }
   ]
  },
  {
   "title": "Network received",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{device!~\"lo\"}[5m]))"
    }
   ]
  },
  {
   "title": "Network transmitted",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{device!~\"lo\"}[5m]))"
    }
   ]
  }
 ]
}